#!/usr/bin/env bash

clip(){ xclip -selection c -o; }
# clip(){ xclip -o; } # use this to watch any selection
folder="/dev/shm/clipsh"
install -d -m 700 $folder
filename="${folder}/$(date +%s)"

# compute clip MD5
clip_md5=$(clip | md5sum | awk '{print $1}')
echo "$clip_md5"

# last clip is still the clipboard
last_clip=$(find ${folder} -type f | head -1)

# first clip ?
[ -z "$last_clip" ] && clip > "$filename" && echo "wrote first clip" && exit 0
last_clip_md5=$(md5sum "$last_clip" |  awk '{print $1}')

[ "$last_clip_md5" == "$clip_md5" ] && echo "clip didnt change" && exit 0

# check if already clipped
already_clipped=$(find $folder -type f -print0 | xargs -0 md5sum |  grep "$clip_md5")
echo "already clipped: $already_clipped"

if [ ! -z "$already_clipped" ]; then
  echo 'promoting duplicate'
  mv "$(echo "$already_clipped"| awk '{print $2}')" "$filename"
else
  echo "adding new clip"
  clip> "$filename"
fi
